### ISSUE TITLE
Minor Cohen parameter

### ISSUE THREAD

**Issue by klainfo** [klainfo/ScottKnottESD#12]
1) Line 44 of Partition.R:
 magnitude <- as.character(cohen.d(a,b)$magnitude)  

Cohen.d allows you to inform whether the observations are paired or not ("paired" parameter). The default is false. However, Ahmed and I think that the observations will be paired most of the time (like in your example dataset). And this paired parameter does affect the 'd' estimate. Hence, one possible fix:

 magnitude <- as.character(cohen.d(a,b, paired = TRUE)$magnitude)    

Better yet, I would include a "paired" parameter in the function sk_esd() with default TRUE.

**Comment by golivax** [comment]
Thanks, Kla! ;-)
