### ISSUE TITLE
Cohen effect size calculation should be paired.

### ISSUE THREAD

**Issue by golivax** [klainfo/ScottKnottESD#16]
Hi Kla. You had fixed this problem (issue #12). However, when doing the refactoring in commit f9b8c83eee22cf0341464f758c4fc59b0e49f69c, you reverted the change and the cohen.d() test became once again non-paired. As I mentioned before, I believe the paired parameter should be true, since I assume most of the time users would be comparing values from different bootstrap iterations. Ideally, the whole paired/non-paired thing should be a parameter to the sk_esd function (e.g., with a default to TRUE).

**Comment by klainfo** [comment]
Thanks. Sorry for the delay. It's not been fixed in https://github.com/klainfo/ScottKnottESD/pull/20 (but not yet update to CRAN, will do soon) - Kla
